### ISSUE TITLE
The builder produces invalid DFA states on grammars with long literals.

### ISSUE THREAD

**Issue by pmarflee** [teo-tsirpanis/Farkle#17]
I'm trying to use Farkle to parse the input for [Advent of Code 2020 Day 7](https://adventofcode.com/2020/day/7).  You can find my current WIP [here](https://github.com/pmarflee/AdventOfCode2020FSharp).  I have a few questions about the implementation of my parser that I hope you can help me with.

Firstly, my parser is failing on the input text _light red bags contain 1 bright white bag, 2 muted yellow bags._ with the following error:

> (1, 9) Cannot recognize character 'd'.

The error seems to be indicating that the text fragment 'light red' can't be parsed.  However, I have a unit test which tests parsing the bag colour and this is passing.  It's not clear to me why the parser I have written can't parse the entire line of text, when the tests I have written for parsing the individual elements of the line all pass.

Secondly, I have written the following parser to parse the word 'bag', which can either be singular or plural:

`        static let bagWord = regexString "bag(s)?" |> terminal "BagWord" (T(fun _ data -> data.ToString()))`

I use it when parsing the name of a bag, e.g. 'light red bags':

`static let bagType = "BagType" ||= [ !@ colour .>>. bagWord => (fun c _ -> c) ]`

It works, but I'm wondering whether there is a better way of doing this.  I'm not really interested in the result of parsing this word.  You can see from the above code fragment that I'm discarding the result.  However it doesn't look as if I can use literal text here, because the word can either be singular or plural.  Do you have any suggestions?

Thirdly, I don't know how to extend the parser so that it can handle the following input when a bag contains no contents:

> faded blue bags contain no other bags.

It looks like I need to use some kind of alternation construct here which tries one type of Farkle and then falls back to using another type if the first one fails.  I see that there is something called `choice` in the library, but this is a low-level construct for Regexes.  I think I would need something that can choose between different Farkles, first trying the one which matches against bags with contents, and then trying the one which matches against bags with no contents if the first one fails.  What can I do here?

Many thanks

Paul

**Comment by teo-tsirpanis** [comment]
Hello Paul,

I took a look at your repository and at the failing test.

When I tested it with my local development edition of Farkle, the test failed with an even more bizarre error:

```
(1, 16) Found 'shiny gold' while expecting one of the following tokens: contain, '.', ','.
```

For some reason, Farkle considered the ~~word~~ character sequence `contai` as `shiny gold`, suggesting a deeper and more serious bug.

I will try to fix it soon, but no sooner than mid-February due to my impending midterm exams. In any case, thanks a lot for this bug discovery!

---

However, I slightly refactored your grammar and the tests passed for no clear reason why. My changes were submitted in pmarflee/AdventOfCode2020FSharp#1.

> I need to use some kind of alternation construct

There is such alternation construct in the `||=` operator! If you write `"Foo" ||= [bar; baz]`, it will recognize either `bar` or `baz`. I implemented `no other bags` in the PR as well.

**Comment by teo-tsirpanis** [comment]
## Initial bug hunting report

Judging from the grammar changes that somehow fixed it, the problem seems to occur on grammars that have _long_ literals.

Without applying them, the bug could not be reproduced on version 5.4.1; Farkle's latest version.

Still I do not recommend to rollback to this version because you would be forced to write regexes the ~~manual~~ painful way, without `regexString`.

**Comment by pmarflee** [comment]
Teo

Thanks for sending me that pull request.  However, after merging it I'm still not able to parse a complete line of text.  The error that I'm getting now when I run the 'Day 7 Parse Line' test is:

> Error while building the grammar: Cannot distinguish between symbols: BagWord, bags. The conflict is caused when two or more terminal definitions can accept the same text.

If I remove the Farkle which matches a bag which contains no other bags, it passes.  I think the parser must not be able to distinguish between the `BagWord` terminal and the literal text "bags" in the alternate construct.  I tried changing that alternate Farkle to

```
!@ bagType .>> "contain" .>> "no" .>> "other" .>> bagWord
            => (fun t -> { Type = t; Contents = [] })
```

but this fails to compile with the error

> This expression was expected to have type 'string' but here has type 'DesigntimeFarkle'

What do you suggest?

Paul

**Comment by teo-tsirpanis** [comment]
The compiler error is related to dotnet/fsharp#7917; I thought it could not reproduce with the `=>` operator at the end.

I used this and it compiled (don't ask me why 😛):

``` fsharp
!@ bagType .>> "contain" .>> "no" .>> "other" |> id .>> bagWord
            => (fun t -> { Type = t; Contents = [] })
```

However, when I ran it the test failed with:

```
(1, 2) Cannot recognize character 'i'
```

This issue is of high severity and I am looking into it.

**Comment by teo-tsirpanis** [comment]
I most likely found the cause of the bug. It comes from [BitCollections](https://github.com/teo-tsirpanis/BitCollections), another library of mine.

I am working towards understanding the bug and fixing it. Thankfully, once it is done, only BitCollections needs to be updated.

**Comment by pmarflee** [comment]
Thanks, I'll wait to hear from you when you have a fix.

**Comment by teo-tsirpanis** [comment]
I released a patch for BitCollections and upon using it, all tests succeeded.

Make sure that BitCollections version 1.0.1 is used and let me know if everything went well.

**Comment by pmarflee** [comment]
Thanks, after updating BitCollections to v1.0.1 I was able to get the tests to pass.  I had to add the following code:

```
static let fullStop = literal "."

!@ bagType .>> "contain" .>> "no" .>> "other" |> id .>> bagWord .>> fullStop
            => (fun t -> { Type = t; Contents = [] })
```
because it wouldn't let me put a literal "." after `bagWord`.  But it's working now which is the main thing.

**Comment by teo-tsirpanis** [comment]
OK, that's great news. I am going to close this issue.

Thanks again @pmarflee for using Farkle and for spotting this bug!

**Comment by teo-tsirpanis** [comment]
# Issue postmortem

Since version 6.0.0, and as an effort to increase the builder's speed, Farkle started using a library named BitCollections to replace the horribly inefficient and tree-based F# `Set`s of integers (and because `System.Collections.BitArray` is inadequate).

However, this library had a bug where _enumerating_ (not performing operations) over collections whose smallest element is at least 128 would produce invalid numbers (decreased my multiples of 64). A reproduction of this bug is shown in LINQPad:

![image](https://user-images.githubusercontent.com/12659251/106160724-cdbe8e80-618e-11eb-9124-5efe5db028c2.png)

> __Note:__ The above snippet uses the `BitCollections.BitArrayNeo` type while the bug was exhibited with enumerations of the `BitCollections.BitSet` type. Both types are affected since they share the same enumeration code.

This bug had not been observed in the past because the grammars under which Farkle was tested were not such complex to use large bit collections. Until now.

## How it occurred

The reporter of this issue was using Farkle to solve some Advent of Code problems and encountered bizarre lexical errors while testing a grammar with long literals. As evidenced during debugging, the DFA builder had created a regex tree with at least 128 leaves, triggering the aforementioned bug.

My first suggestions was to use more but smaller literals by breaking them into words (a generally good practice since it allows an arbitrary number of whitespace between them). Unbeknownst to me at that point, the new grammar's regex tree had less than 128 leaves and the bug did not reproduce. When however I implemented a missing feature from the Advent of Code challenge, the regex tree's leaf count increased and the bug appeared again.

## How it was found

Because the bug did not reproduce on Farkle 5.4.1, my suspicions fell on BitCollections.

To verify these suspicions, I used my local Farkle repository and replaced all instances of `BitCollections.BitSet` in the DFA builder with the formerly used `Set<int>`. I ran the tests and they succeeded. Bingo!

With the culprit being found, I shimmed the `Set.union` function to perform the set union in both bit sets and F# sets, compare the result and throw an exception if they are different. I ran the tests under a debugger, with the breakpoint placed at the failure point:

![image](https://user-images.githubusercontent.com/12659251/106160939-0d857600-618f-11eb-9cef-005ff6d9d048.png)

See the underlined numbers? The F# set says it holds only the number 132, but the bit set says it contains only 68.

However, by looking at the bit set's hexadecimal representation, the 132th bit is on, not the 68th. Which means that the bit set correctly stores the number 132, but outputs the wrong one when _enumerated_. It is now sure that the problem originates in `BitSet`'s enumerator.

## How it was fixed.

https://github.com/teo-tsirpanis/BitCollections/commit/33c585a53e0edd7f03518ec024cb2ab337a2f495 in BitCollections fixed the enumerator bug. Moreover it modified a test to ensure that regressions do not happen.

With some more minor fixes, BitCollections version 1.0.1 was released. When a stable version of Farkle 6 gets released, it will require at least that version of BitCollections.
